version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'

  publisher:
    build:
      context: ./RabbitMQPubSubAPI
      dockerfile: Dockerfile-publisher
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq
      - consumer
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
 

  consumer:
    build:
      context: ./RabbitMQPubSubCli
      dockerfile: Dockerfile-consumer
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest

